A big update for all southern routes
Sp3EdeR/huroutes pull request #75
Opened 2022-05-02 13:08 UTC by Sp3EdeR

Note for reviewer: https://kmlviewer.nsspot.net/ can be used to open KML files online.

2022-05-02 14:46 UTC, Csempi commented on data/6.md
> +A Mecseknádasd és Hird közötti szakasza a 6-os útnak kellemesen, enyhén kanyargós, tempós útszakasz. Sajnos igen nagy forgalom várható, illetve akadnak kereszteződések ahol nagyon figyelni kell a kan
"kellemesen" helyett "kellemes" jobban illik a szövegbe, vagy pedig így: ... enyhén, de kellemesen kanyargós....")
"...illetve akadnak kereszteződések, ahol nagyon figyelni kell..." (ahol elé vessző)

2022-05-02 14:46 UTC, Csempi commented on data/Kurd.md
> +A Dunántúli dombság egy rejtett autós kincsét fedezhetjük fel ezen a kis szakaszon. Az útszakasz alsó (északi) fele fekete, míg a felsőbb része fehér aszfaltos. A fehér aszfaltos rész, bár nem extrém
"Dunántúli-dombság"
"extrém módon"

2022-05-02 14:46 UTC, Csempi commented on data/PecsOrfu.md
> +A Ranga László út nagyon jó vonalvezetésű, jó minőségű, kellemesen széles út. Összességében az ország egyik legjobb szerpentinje. Egyetlen probléma, hogy közepes-erős forgalom várható, és a biztonság
"Egyetlen probléma, hogy közepes-erős forgalom várható, és a biztonságos előzési lehetőségek relatív ritkasága." helyett: "Az útvonal nagy problémái a várható közepes-erős forgalom és a biztonságos előzési lehetőségek ritkasága."

2022-05-02 14:46 UTC, Csempi commented on data/PecsOrfu.md
> +A térképen javasolt útvonal a 6604-es úton folytatódik, az Orfűi lehajtó után, egy kevésbé forgalmas, de nagyon szép kerülőt javasol. Lehetséges lekanyarodni Orfű irányába a Kossuth Lajos utcára is n
"Orfűi lehajtó" helyett "orfűi lehajtó"

2022-05-03 00:30 UTC, nbali commented on data/AbaligetHetvehely.md
> +Enyén kanyargó aszfaltcsík hömpölyög szép dombok és erdők közepette, ezen szakasz alatt. Bár Abaliget után nagyon rossz az útminőség egy rövidke szakaszon, hamar nagyon jó minőségűre és igazán élvezh
"Enyhén"
"közepette ezen"

2022-05-03 00:31 UTC, nbali commented on data/Kurd.md
> +A Dunántúli-dombság egy rejtett autós kincsét fedezhetjük fel ezen a kis szakaszon. Az útszakasz alsó (északi) fele fekete, míg a felsőbb része fehér aszfaltos. A fehér aszfaltos rész, bár nem extrém
"rész - bár nem extrém módon - de"

2022-05-03 00:34 UTC, nbali commented on data/MagyarhertelendOrfu.md
> +Szép, dimbes-dombos, mezőkkel tarkított tájon kanyarog gyengéden Magyarhertelend és Orfű között ez az útszakasz. A kissé fehéres aszfalton a tapadás csökkentett mértékű. A forgalom sokkal alacsonyabb
"csökkent*"

2022-05-03 00:38 UTC, nbali requested changes
.

2022-05-03 05:40 UTC, Sp3EdeR commented
Closes #73 
Closes #74

2022-05-03 06:07 UTC, nbali approved these changes

2022-05-04 16:36 UTC, merged