Updated Balaton-felvidek
Sp3EdeR/huroutes pull request #98
Opened 2022-07-20 11:41 UTC by Sp3EdeR

Note for reviewer: https://kmlviewer.nsspot.net/ can be used to open KML files online.

2022-07-20 15:15 UTC, Dpx86 commented on data/BalatonFelvidek.md
> +Ez a bejáróút egy sokkal érdekesebb, izgalmasabb alternatíva Veszprém és Tapolca összekötésére a [77-es útnál](#77). Az útvonal mentén végig változatos, gyönyörű kilátásokban lehet részünk, miközben
Szvsz ez a szórennd olvasmányosabb: Ez a bejáróút a 77-es útnál sokkal érdekesebb...
Kicsit sok a jelző én nem tudom érthetően összeolvasni ezt a részt:
"A bejáróút szakaszai a tempós, erdei [73-as út](#73), a [Füred és Tótvázsony közti](#BalatonfuredTotvazsony) szőlők közti kanyargós és a [Tótvázsony és Dörgicse](#TotvazsonyDorgicse) illetve [Köveskál és Gyulakeszi](#KoveskalGyulakeszi) közti bukkanós-kanyargós, gyönyörű kilátású szakaszok." 

Talán ";" -vel. --> A bejáróút szakaszai a tempós, erdei [73-as út](#73), a [Füred és Tótvázsony közti](#BalatonfuredTotvazsony) szőlők közti kanyargós; a [Tótvázsony és Dörgicse](#TotvazsonyDorgicse); illetve [Köveskál és Gyulakeszi](#KoveskalGyulakeszi) közti bukkanós-kanyargós, gyönyörű kilátású szakaszok. <-- Vagy akár külön külön mondatokban felsorolva?

2022-07-20 15:17 UTC, Dpx86 commented on data/BalatonFelvidek.md
> +A bejáróút felfúzhető körtúrába a [77-es úttal](#77), bár ez kevésbé izgalmas útvonal.
A bejáróút felfűzhető a - kevésbé izgalmas -  [77-es úttal](#77) is a körtúrába.

2022-07-20 15:19 UTC, Dpx86 commented on data/BalatonFelvidek.md
> +Balatonfüreden például érdemes lehet megállni egy séta erejére a festői [Tagore sétányon](https://welovebalaton.hu/hely/balatonfuredi-tagore-setany) és a mellette lévő [gyógy téren](https://goo.gl/ma
"lehet" nem kell

2022-07-20 15:23 UTC, Dpx86 commented on data/KoveskalGyulakeszi.md
> +Jó minőségű aszfalt fedi e szakaszt, mindössze csak néhol ráz picit a széle. Az enye ívű kanyarokat számos bukkanó teszi érdekesebbé, izgalmasabbá. Az útvonal végig nyílt, mezős-földes kilátással vis
"Az enyhe" kimaradt a h

2022-07-20 15:27 UTC, Dpx86 commented on data/BalatonfuredTotvazsony.md
> +Nagyon jó burkolat felett suhanhatunk tova a szőlők, mezők között és erdőben, ezen a panorámás útszakaszon, miközben egymás után hágunk meg dombokat. Főként enyhe, tempós kanyarok vannak ezen a szaka
Szórend + az: 
Ezen a panorámás útszakaszon nagyon jó burkolat felett suhanhatunk tova a szőlők, mezők között és **az** erdőben, miközben egymás után hágunk meg dombokat. Főként enyhe, tempós kanyarok vannak ezen a szakaszon. Kifejezetten alacsony forgalomra lehet számítani.

2022-07-20 15:31 UTC, Dpx86 commented on data/TotvazsonyDorgicse.md
> +Ez a bukkanókkal és kanyarokkal dús, szakasz keresztülszeli a balatonfelvidéki dombságot a völgyein át. Bár a kanyarok nagyrészt enyhék, a bukkanók változatossá és érdekessé teszik a szakaszt, de pon
Ez a bukkanókkal és kanyarokkal dús szakasz keresztülszeli a balatonfelvidéki dombságot a völgyein át. Bár a kanyarok nagyrészt enyhék, a bukkanók mégis változatossá és érdekessé teszik a szakaszt. Azonban pont emiatt, fokozott figyelmet igényel, hogy a nehezen belátható részeken ne érjen minket meglepetés. Pécsely előtt egy rövid szakasz kivételével Tótvázsony és Pécsely között az útminőség nagyrészt jó-közepes. Pécselyt követően viszont tökéletes útminőséget élvezhetünk Dörgicséig. Az út mentén nagyrészt szép mezőkhöz, földekhez és domboldalakhoz lesz szerencsénk.

2022-07-20 15:33 UTC, Dpx86 reviewed
Pár részt átfogalmaztam és írtam bele ajánlásokat, ami mentén érdemes lenne átfogalmazni

2022-07-20 20:09 UTC, nbali requested changes

2022-07-20 20:09 UTC, nbali commented on data/BalatonFelvidek.kml
> +    <name>Balatonfelvidék</name>
[Balaton-felvidék](https://hu.wikipedia.org/wiki/Balaton-felvid%C3%A9k)

2022-07-20 20:09 UTC, nbali commented on data/BalatonFelvidek.kml
> +      <name>Balatonfelvidék</name>
[Balaton-felvidék](https://hu.wikipedia.org/wiki/Balaton-felvid%C3%A9k)

2022-07-20 22:27 UTC, nbali reviewed
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sp3eder/huroutes/98)* status: all files reviewed, 10 unresolved discussions (waiting on @miklospuspan and @Sp3EdeR)



<!-- Sent from Reviewable.io -->

2022-07-21 13:11 UTC, Sp3EdeR commented on data/BalatonFelvidek.kml
> +      <name>Balatonfelvidék</name>
Ugyanaz mint a másiknál

2022-07-22 05:06 UTC, Dpx86 approved these changes

2022-07-22 05:06 UTC, merged